### ISSUE TITLE
about the evaluating patches of multiple patches pass test

### ISSUE THREAD

**Issue by kangyunxuan** [ASSERT-KTH/repairllama#8]
Hi,

I am working on reproducing the results from the paper, but it seems that the patch evaluation process hasn’t been made public yet. 
I'm curious whether, during the patch assessment stage, there can be multiple candidate patches that pass the tests. If so, how do you handle it and choose the best patch?

**Comment by andre15silva** [comment]
Hi @kangyunxuan,

We do not choose the best patch. We consider a bug fixed, according to a certain metric, if there is at least one patch that fits the criteria of that metric.

So, for the results we report, it does not matter if one or five candidates pass the tests: the bug is considered as plausibly fixed.

For the code to reproduce the evaluation process, please refer to https://github.com/ASSERT-KTH/elle-elle-aime
We do not currently have the exact commands to run given the files in this repo due to ongoing development, but you can see the code used by the "evaluate_patches.py" script.

**Comment by kangyunxuan** [comment]
Got it, thank you for the detailed explanation.

**Comment by kangyunxuan** [comment]
Hi @andre15silva , 
I’m currently using the defects4j_f2f_bugs_with_ir4.jsonl file with llama_pred.py to generate patches. However, I’ve encountered some single-function bugs that exceed the maximum token limit, making it unable to generate patches for them. I only have 335 bugs that were successfully generated with patches, I think it's because some bugs were skipped for exceeding the maximum length.
Could you please share how you handle generating patches for these kinds of bugs? Thanks!

**Comment by andre15silva** [comment]
Are you considering input + output length, or just input length?
